---
runtime: python39
instance_class: F1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  FLASK_SECRET_KEY: 'projects/image-flipper001/secrets/flask_secret_key/versions/latest'
